export const OriginCategorieList = [
  "Candle holder",
  "Home decoration",
  "Ashtray",
  "Lighter cover",
  "Tissue box",
  "Vases",
  "Storage box decor",
  "Parfum stand",
  "Frame decoration",
  "Jewelry tray",
  "Plant pots",
  "Table lamp",
  "Essentiel Oil bottle",
  "Diffuser",
  "Oud burner",
  "Event items",
  "Customized gifts",
];
